# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='publisher',
        ),
    ]
